[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "codelens"
path = "src/main.rs"

[dependencies]
dotenv = "0.15.0"
inquire = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "2.9", features = ["json"] }
